sudo: false

language: node_js

node_js:
  - "4.2"

before_script:
  - npm install
  - npm install jshint

script:
  - npm run lint
  - istanbul cover -x **/lib/** ./node_modules/mocha/bin/_mocha test/rpc.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
